// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class AgentCategoryDocument
{
    public int DocumentId { get; set; }

    public int? AgentCategoryTypeId { get; set; }

    public int? DocumentTypeId { get; set; }

    public virtual AgentCategoryType AgentCategoryType { get; set; }

    public virtual ICollection<ContractDocument> ContractDocuments { get; set; } = new List<ContractDocument>();

    public virtual DocumentType DocumentType { get; set; }
}