// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class ContractReviewDetail
{
    public int Id { get; set; }

    public int ContractId { get; set; }

    public string ReviewRemarks { get; set; }

    public string ReviewedBy { get; set; }

    public string ReviewStatus { get; set; }

    public DateOnly? ReviewedDate { get; set; }

    public virtual ContractDetail Contract { get; set; }
}