// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class ContractDetail
{
    public int Id { get; set; }

    public string ContractId { get; set; }

    public DateOnly ContractDate { get; set; }

    public string AgentId { get; set; }

    public string ContractSummary { get; set; }

    public int? Quantity { get; set; }

    public string EntityCode { get; set; }

    public DateOnly DeliveryStartDate { get; set; }

    public DateOnly DeliveryEndDate { get; set; }

    public DateOnly ContractApprovedDate { get; set; }

    public string Reviewer { get; set; }

    public int StatusId { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public virtual User Agent { get; set; }

    public virtual ICollection<ContractDocument> ContractDocuments { get; set; } = new List<ContractDocument>();

    public virtual ICollection<ContractReviewDetail> ContractReviewDetails { get; set; } = new List<ContractReviewDetail>();

    public virtual ICollection<ContractStatusHistory> ContractStatusHistories { get; set; } = new List<ContractStatusHistory>();

    public virtual Entity EntityCodeNavigation { get; set; }

    public virtual ICollection<FarmDetail> FarmDetails { get; set; } = new List<FarmDetail>();

    public virtual ContractStatus Status { get; set; }
}