// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class ContractDetailsDailyLoad
{
    public int Id { get; set; }

    public string ContractId { get; set; }

    public DateOnly? ContractDate { get; set; }

    public string AgentId { get; set; }

    public string ContractSummary { get; set; }

    public int? Quantity { get; set; }

    public string EntityCode { get; set; }

    public DateOnly? DeliveryStartDate { get; set; }

    public DateOnly? DeliveryEndDate { get; set; }

    public DateOnly? ContractApprovedDate { get; set; }

    public string UpstreamSystem { get; set; }

    public bool IsProcessed { get; set; }

    public string ErrorDetails { get; set; }

    public DateOnly? CreatedDate { get; set; }
}