// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class DocumentType
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<AgentCategoryDocument> AgentCategoryDocuments { get; set; } = new List<AgentCategoryDocument>();
}