// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class FarmDetail
{
    public int FarmId { get; set; }

    public int ContractId { get; set; }

    public string FarmName { get; set; }

    public string GeoLocationCoordinates { get; set; }

    public int? Area { get; set; }

    public string FarmPolygon { get; set; }

    public virtual ContractDetail Contract { get; set; }
}