// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Volcafe.Core.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public int? UserTypeId { get; set; }

    public int? UserRoleId { get; set; }

    public string AgentId { get; set; }

    public int? AgentCategoryTypeId { get; set; }

    public string Reviewer { get; set; }

    public string Address { get; set; }

    public string ContactNumber { get; set; }

    public bool? Active { get; set; }

    public DateOnly? LastLogin { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public DateOnly? ModifiedDate { get; set; }

    public virtual AgentCategoryType AgentCategoryType { get; set; }

    public virtual ICollection<ContractDetail> ContractDetails { get; set; } = new List<ContractDetail>();

    public virtual UserRole UserRole { get; set; }

    public virtual UserType UserType { get; set; }
}